version: "3.9"

services:
  web:
    image: ghcr.io/mehdihassaniir/pnuseat:latest
    container_name: PnuSeatWeb
    ports:
      - "18080:80"
    environment:
      DB_HOST: db
      DB_NAME: PnuExamsSeatNumber
      DB_USER: pnu_user
      DB_PASS: change_me
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - PnuSeat_Network

  db:
    image: mysql:8.0
    container_name: PnuSeatDB
    environment:
      MYSQL_ROOT_PASSWORD: super_secure_root
      MYSQL_DATABASE: PnuExamsSeatNumber
      MYSQL_USER: pnu_user
      MYSQL_PASSWORD: change_me
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - /root/docker/Nesaar/db_data:/var/lib/mysql
      - /root/docker/Nesaar/docker/mysql-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - PnuSeat_Network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: PnuSeatPhpMyAdmin
    restart: unless-stopped
    ports:
      - "18081:80"
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: http://localhost:18081/
    depends_on:
      - db
    networks:
      - PnuSeat_Network

volumes:
  db_data:

networks:
  PnuSeat_Network: